"""

Also look at typer based build deploy test and doc generation
  + https://typer.tiangolo.com/tutorial/package/

Look in tooling/tasks.py
  + The invoke based task management is python based solution for project
    management as was auto generated by pypackage-cookiecutter but typer also
    provides modern ways of doing the same ...

Here we can build a tool to do below things
  + add dependencies (poetry add)
  + poetry build
  + poetry test
  + poetry publish
  + poetry docs generation
  + tasks.py clean ..... bla bla bla

We aim to build some tool that can perform some package management for u...

This might be a huge task so LOW priority ... only do when u fully use poetry
and invoke based project management ... then do small project for own
libraries and then move for big tool ...


"""
