

name: coverage


on:

  push:
    branches: [ main, ]
  pull_request:
    branches: [ main, ]


  workflow_dispatch:


jobs:

  test:

    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # know more at https://github.com/snok/install-poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0a2
          virtualenvs-create: true
          virtualenvs-in-project: false
          # virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      - name: Install test dependencies
        run: poetry install --with test

      - name: Test with PyTest and get coverage report
        run: poetry run pytest --cov=./ --cov-report=xml

      # know more at https://github.com/codecov/codecov-action
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#          files: ./coverage1.xml,./coverage2.xml # optional
#          flags: unittests # optional
          name: codecov_report
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
