name: ssssss

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
        default: "world"

jobs:
  show_inputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
