

name: pre-commit workflow


on:

  push:
    branches: [ main, ]
  pull_request:
    branches: [ main, ]


  workflow_dispatch:


jobs:

  code-coverage:

    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # know more at https://github.com/snok/install-poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0a2
          virtualenvs-create: true
          virtualenvs-in-project: false
          # virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      - name: Install pre-commit dependencies
        run: poetry install --with pre-commit

      - name: Perform pre-commit tests
        run: poetry run pre-commit run
